# Generated by Django 3.0.4 on 2020-03-19 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20200319_1756'),
        ('accounts', '0002_auto_20200319_1756'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='server',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='accounts.Account'),
        ),
        migrations.AddField(
            model_name='server',
            name='projects',
            field=models.ManyToManyField(related_name='servers', to='projects.Project'),
        ),
    ]
