# Generated by Django 3.0.4 on 2020-03-17 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('servers', '0002_server_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='servernote',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='servers.Server'),
        ),
    ]
