# Generated by Django 3.0.4 on 2020-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20200317_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
