# Generated by Django 3.0.4 on 2020-03-18 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vapor_manager.servers.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servers', '0005_server_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverfile',
            name='filename',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serverfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serverfile',
            name='file',
            field=models.FileField(max_length=512, upload_to=vapor_manager.servers.models.account_server_path),
        ),
    ]
