# Generated by Django 3.0.4 on 2020-03-17 20:14

from django.db import migrations, models
import vapor_manager.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(max_length=512, upload_to=vapor_manager.projects.models.account_project_path),
        ),
    ]
