# Generated by Django 3.0.4 on 2020-03-18 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20200317_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='filename',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
