# Generated by Django 3.0.4 on 2020-03-18 14:44

from django.db import migrations, models
import vapor_manager.tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200318_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(max_length=512, upload_to=vapor_manager.tasks.models.account_task_path),
        ),
    ]
