# Generated by Django 3.0.4 on 2020-03-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Account'),
        ),
        migrations.AddConstraint(
            model_name='clientcontact',
            constraint=models.UniqueConstraint(fields=('client', 'is_primary'), name='unique primary contact'),
        ),
    ]
