# Generated by Django 3.0.4 on 2020-03-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientcontact_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'ordering': ['is_primary']},
        ),
        migrations.RemoveConstraint(
            model_name='clientcontact',
            name='unique primary contact',
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='clientnote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.Client'),
        ),
    ]
