# Generated by Django 3.0.4 on 2020-03-17 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('clients', '0004_auto_20200316_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontact',
            options={'ordering': ['-is_primary', 'created']},
        ),
        migrations.AlterField(
            model_name='client',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='users.Account'),
        ),
    ]
